Repository lidiannerb/SAP007-burger-queen-api-client, pull requests merged in 2022-06, with the labels that each got.

#25 feat: WIP/ style-menu
  src/components/SelectTable/index.jsx
  src/components/button/style.css
  src/components/card/index.jsx
  src/components/card/style.css
  src/components/header/index.jsx
  src/components/header/style.css
  src/pages/menu/index.jsx
  src/pages/menu/style.css
  src/style/global.css
Labels: feat

#26 feat: adding style to the page menu and components
  src/components/SelectTable/index.jsx
  src/components/SelectTable/styles.css
  src/components/button/style.css
  src/components/card/index.jsx
  src/components/card/style.css
  src/components/comand/index.jsx
  src/components/comand/style.css
  src/components/inputs/style.css
  src/pages/login/index.jsx
  src/pages/menu/index.jsx
  src/pages/menu/style.css
  src/pages/register/index.jsx
  src/style/global.css
Labels: feat

#27 feat: component errors - adjustments
  src/components/errorMessages/index.jsx
  src/components/errorMessages/style.css
  src/pages/login/index.jsx
  src/pages/menu/index.jsx
  src/pages/menu/style.css
  src/pages/register/index.jsx
  src/services/errors/index.js
Labels: feat

#28 feat: WIP feat- remove order sent
  src/components/comand/index.jsx
  src/pages/menu/index.jsx
  src/services/handleLogout/index.js
Labels: feat

#29 feat: WIP feat-kitchen-page-in-progress
  src/components/SelectTable/index.jsx
  src/components/comand/index.jsx
  src/components/header/index.jsx
  src/pages/kitchen/index.jsx
  src/pages/kitchen/style.css
  src/pages/login/index.jsx
  src/pages/menu/index.jsx
  src/routes.jsx
  src/services/handleLogout/index.js
Labels: feat

#30 feat: WIP - menu hamburguer
  src/components/button/style.css
  src/components/header/index.jsx
  src/components/header/style.css
  src/components/navbar/index.jsx
  src/components/navbar/style.css
Labels: feat

#31 feat: add private route
  src/routes.jsx
Labels: feat

#32 feat: fix-logout
  src/components/navbar/style.css
Labels: bug

#33 fix: adding routes on register page
  src/components/layout/style.css
  src/pages/login/index.jsx
  src/pages/register/index.jsx
Labels: feat

#34 fix: refactor image
  src/assets/heisenburger.svg
Labels: bug

#35 test: testing component Button
  src/components/button/test.js
  src/test/App.test.js
Labels: test

#37 test: testing components
  src/components/card/card.test.js
  src/components/errorMessages/error.test.js
  src/components/header/header.test.js
  src/components/inputs/inputs.test.js
  src/components/layout/layout.test.js
  src/components/logo/logo.test.js
  src/components/navbar/navbar.test.js
Labels: test

#40 feat: WIP - add page kitchen
  src/components/cardOrder/index.jsx
  src/components/cardOrder/style.css
  src/pages/kitchen/index.jsx
  src/pages/kitchen/style.css
  src/pages/menu/index.jsx
  src/services/data/index.js
Labels: feat

#41 feat: filters button changes color when selected
  src/pages/menu/index.jsx
Labels: feat

#42 feat: WIP - add feature cardOrder
  src/components/card/index.jsx
  src/components/cardOrder/index.jsx
  src/pages/kitchen/index.jsx
Labels: feat

#44 feat: WIP update status
  src/components/cardOrder/index.jsx
  src/pages/kitchen/index.jsx
  src/services/data/index.js
Labels: feat

#45 feat: WIP add status in orders
  src/pages/kitchen/index.jsx
  src/services/data/index.js
Labels: feat

#46 feat: update status
  src/pages/kitchen/index.jsx
Labels: feat

#49 feat: serve orders done
  src/pages/readyOrders/index.jsx
Labels: feat

#50 feat: WIP sorted orders
  src/pages/readyOrders/index.jsx
Labels: feat

#51 feat: ordering and add button on orders done
  src/components/cardOrder/index.jsx
  src/pages/kitchen/index.jsx
  src/pages/login/index.jsx
  src/pages/menu/index.jsx
  src/pages/readyOrders/index.jsx
  src/pages/register/index.jsx
Labels: feat

#53 fix: orders served
  src/pages/kitchen/index.jsx
Labels: fix

#54 feat: WIP style pages
  src/components/button/style.css
  src/components/card/index.jsx
  src/components/cardOrder/index.jsx
  src/components/cardOrder/style.css
  src/pages/kitchen/index.jsx
  src/pages/kitchen/style.css
Labels: feat

#57 fix: preparationTime
  src/components/cardOrder/index.jsx
Labels: fix

#58 doc: add readme
  README.md
  README.old.md
  Readme/Lidianne.jpg
  Readme/Prototipos.jpeg
  Readme/Taila.png
  Readme/Trello.png
Labels: documentation

#59 doc: add readme adjustments
  README.md
Labels: documentation
